name: disent
channels:
  - conda-forge
  - menpo
dependencies:
  - python=3.12
  - numpy
  - opencv
  - pytorch
  - loguru
  - torchvision
  - notebook
  - ipykernel
  - jupyterlab
  - matplotlib
  - albumentations==1.4.20
  - timm
  - torchinfo
  - jupyter
  - ipywidgets
  - click
  - lightning
  - tensorboard
  - lightly
