name: disent
channels:
  - conda-forge
dependencies:
  - albumentations==1.4.20
  - click
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - kornia
  - lightly
  - lightning
  - loguru
  - matplotlib
  - notebook
  - numpy
  - opencv
  - python=3.12
  - pytorch
  - scikit-learn
  - streamlit
  - tbparse
  - tensorboard
  - timm
  - torchinfo
  - torchvision
  - pip:
    - DISTS-pytorch==0.1
    - faiss-cpu==1.10.0
